### ISSUE TITLE
To handle JobInstanceAlreadyCompleteException if used in composed task

### ISSUE THREAD

**Issue by atulkulkarni18** [spring-cloud-task-app-starters/timestamp-batch#16]
When timestamp-batch is used in composed task, then that composed task can be executed only once. If launched again, results into JobInstanceAlreadyCompleteException.
Logs attached: [logs-from-timestamp-batch-qdzzo499rj-in-timestamp-batch-qdzzo499rj.txt](https://github.com/spring-cloud-task-app-starters/timestamp-batch/files/3089219/logs-from-timestamp-batch-qdzzo499rj-in-timestamp-batch-qdzzo499rj.txt)

To fix this issue, RunIdIncrementer can be set as incrementer.

Note: I have fixed this issue locally and updated test case accordingly. Can this issue be assigned to me?

**Comment by cppwfs** [comment]
Actually this is the desired behavior for a Composed Task Run.    In that the composed-task-runner  can restart specific task execution if it fails.  For example if I have `AAA && BBB && CCC` , and `AAA` runs successfully, but `BBB` fails, we want to re-launch that specific execution such that it will start at `BBB` and once successful, the CTR will then launch `CCC`.   

Composed Task Runner is built using Spring Batch, and if you want to run a new Composed Task Runner instance you can create a new definition, or add/update arguments for each launch, or set the RunIdIncreementer as you show above.

**Comment by cppwfs** [comment]
In this case this is the desired behavior.  We want to show users how batch app works independent, of a composed task execution.  However, you can create a document PR (add to the docs), to discuss how a user can utilize `RunIdIncrementer` to allow the app to be launched multiple times each having its own JobInstance.

**Comment by atulkulkarni18** [comment]
Sure, will raise document PR soon.

**Comment by atulkulkarni18** [comment]
@cppwfs have raised PR. Kindly let me know.

**Comment by atulkulkarni18** [comment]
Closing this issue, as PR is merged to master.
